databases:
  - name: ngao_db
    plan: free
    databaseName: ngao_db
    user: ngao_user

services:
  - type: web
    plan: free
    name: ngao_api
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ngao_core.wsgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ngao_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4